# Generated by Django 3.2.16 on 2022-11-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('not_done', 'Not Done'), ('in_progress', 'In Progress'), ('done', 'Done')], default='not_done', max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('estimated', models.PositiveIntegerField(blank=True, null=True)),
                ('last_done', models.DateField(blank=True, null=True)),
                ('repeat_task', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
