# Generated by Django 3.2.16 on 2022-11-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
