# Generated by Django 3.2.16 on 2022-11-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_estimated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
