# Generated by Django 3.2.16 on 2022-11-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_estimated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
