# Generated by Django 3.2.16 on 2022-11-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_estimated'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_done',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
