# Generated by Django 3.2.16 on 2022-11-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_last_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='last_done',
        ),
    ]
