# Generated by Django 3.2.16 on 2022-11-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_task_last_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_done',
            field=models.DateField(auto_now=True),
        ),
    ]
