# Generated by Django 3.2.16 on 2022-11-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_last_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_done',
            field=models.DateField(blank=True, null=True),
        ),
    ]
