# Generated by Django 3.2.16 on 2022-11-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_task_last_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat_task',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
